sudo: false
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: xjoO7LxuP664AiapOrQyDffNhxaguKuZQX+bGXRfpZbN0FCJzBuE49hkGyvpsF9nHVvLjv21alHsa1x4tP5klTb4r9MsMMWIX4cMdJ6aBL2UGTquYfqpWRfazaUyP2YTpuxc7NrAN9QGbZWGOa3iUDxAOBLTpjhcHeJnkvRbreTwDIXZ7Qc6VS9jztN/vmn+bEpQ9nR7EPkRPqgJz0Hb++M1fnYMU6LsYSJFyNim1Ur1yiZBavYLCOdHnOupFkn0bta2kCk+GDqj1375TlSrExgPjI9LdwsAgL7or0fPUX48tDH/aknOt/hNDSE0OAEgTNzygCV57e8YkuIgA+AosYoO+P0ZTNySnrqyniS51NNYY0b98058sedSCfldtZYxoAbLl93CP84VyNp1HU7WysprpIHLxx69l/K2q4vH2SNKg2aK6W+NaPm3aRVP5O8D+QtobBfiMq9ToUJzr1upe8er2+bJ4JWx/bH4oSzKqAJTK+8ImM48unkMbRJnS8mkoxl6R9f46UT20D6ebZDLQh0+ZdzmXI0rQhl7VIkpQEswRC3jqObgv/dL+MGjFFYJVOA/fUr92hIykIzvTC5CzTZYYINENAIcSCepFx9RVNpFBE4JR6hF238/xEYhw0vFPPyl5+b9uTutIkxumqlnPscIZapY1BGG2ahrh005BBM=
  - secure: AO+0UfQ3sAhyQPd+WZ+6u9wlNrGJOnEEf9Gz7XsriSh6nS0YH7aUMl3tP1+GwvVqzckBZfQUuO3mhF20S/HIsl2G53zNADXrfvGggMmQ+5+C4T0LLYIhrCUlUzQCtpaIqagdXqL7ejAQtM8NiO8/xrB3PduALH/IKM0sbAtSvZtFV/48/3ZTlMUxibHe3oERVJwgk+/LEfkYasV9ay0E50iiGx2wfDFtyRXjPQbxtL3bmwjAcvUkuldaF6vVO4161a+IlpIoHFoKtg4F11DuGfJnZZtNMcwoKHRWo2Gzqh5V/fezsuw6hUf0+oA12dFnsR3jD+VAIFE1WD5djRnBftShlv3e8IzWAXOEOfdYDo82KpA+Ft5xyOexNs1wOcPTffIQ+lVBqnHt7w7r40AeScp0+dSJAGEI/rQnI80nHsKhGPAGGnh+s5p4y4mqGtctvJV/ajltxWwcRg6Sj1AthDpprtWMIzjTYK1Um57fyQNJ2Ts7ierIFpk3GE4IVHblT+s7ZsT4/hhsHMtSW+6lbJy3OVdVEITcV52duORDER3j4cL0TZdOVBksJO5yCOcGM9yi/WrQAwZdYFLUdNn3N/aTAYb//i54l7fD57IE8mJKpYi5SWw/T3TxYt3x7Ftef36KZzetUjTlyJaa+HQYMLcA00PdJBQhWg0Ew9b6o/4=
